/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro-empresa'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasJobIdRouteImport } from './routes/vagas.$jobId'
import { Route as CursosCourseIdRouteImport } from './routes/cursos.$courseId'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro-empresa',
  path: '/cadastro-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasJobIdRoute = VagasJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => VagasRoute,
} as any)
const CursosCourseIdRoute = CursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CursosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/cursos': typeof CursosRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/profissional': typeof ProfissionalRoute
  '/vagas': typeof VagasRouteWithChildren
  '/cursos/$courseId': typeof CursosCourseIdRoute
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/cursos': typeof CursosRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/profissional': typeof ProfissionalRoute
  '/vagas': typeof VagasRouteWithChildren
  '/cursos/$courseId': typeof CursosCourseIdRoute
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/cursos': typeof CursosRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/profissional': typeof ProfissionalRoute
  '/vagas': typeof VagasRouteWithChildren
  '/cursos/$courseId': typeof CursosCourseIdRoute
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/cursos'
    | '/empresa'
    | '/feed'
    | '/login'
    | '/planos'
    | '/profissional'
    | '/vagas'
    | '/cursos/$courseId'
    | '/vagas/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/cursos'
    | '/empresa'
    | '/feed'
    | '/login'
    | '/planos'
    | '/profissional'
    | '/vagas'
    | '/cursos/$courseId'
    | '/vagas/$jobId'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/cursos'
    | '/empresa'
    | '/feed'
    | '/login'
    | '/planos'
    | '/profissional'
    | '/vagas'
    | '/cursos/$courseId'
    | '/vagas/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  CursosRoute: typeof CursosRouteWithChildren
  EmpresaRoute: typeof EmpresaRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  ProfissionalRoute: typeof ProfissionalRoute
  VagasRoute: typeof VagasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-empresa': {
      id: '/cadastro-empresa'
      path: '/cadastro-empresa'
      fullPath: '/cadastro-empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$jobId': {
      id: '/vagas/$jobId'
      path: '/$jobId'
      fullPath: '/vagas/$jobId'
      preLoaderRoute: typeof VagasJobIdRouteImport
      parentRoute: typeof VagasRoute
    }
    '/cursos/$courseId': {
      id: '/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/cursos/$courseId'
      preLoaderRoute: typeof CursosCourseIdRouteImport
      parentRoute: typeof CursosRoute
    }
  }
}

interface CursosRouteChildren {
  CursosCourseIdRoute: typeof CursosCourseIdRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosCourseIdRoute: CursosCourseIdRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

interface VagasRouteChildren {
  VagasJobIdRoute: typeof VagasJobIdRoute
}

const VagasRouteChildren: VagasRouteChildren = {
  VagasJobIdRoute: VagasJobIdRoute,
}

const VagasRouteWithChildren = VagasRoute._addFileChildren(VagasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  CursosRoute: CursosRouteWithChildren,
  EmpresaRoute: EmpresaRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  ProfissionalRoute: ProfissionalRoute,
  VagasRoute: VagasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
